name: husky_hunt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  camera: ^0.10.5+9
  emoji_picker_flutter: ^4.3.0
  f: ^0.1.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^14.0.1
  http: ^1.4.0
  intl: any
  isar:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: 3.1.8
  build_runner: 

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/uw_campus_map.png
    - lib/assets/buildings.json
